### ISSUE TITLE
Request for Data Processing Scripts

### ISSUE THREAD

**Issue by Rivflyyy** [aizhiqi-work/MM-KWS#5]
Hello,

First and foremost, I would like to express my sincere admiration and respect for this work！

I am trying to replicate the data processing steps, specifically converting WenetSpeech to WenetPhrase and LibriSpeech to LibriPhrase. Could you please share the scripts or detailed procedures used for these transformations?

Thank you!

**Comment by aizhiqi-work** [comment]
we update the data pipeline into this repo

**Comment by aizhiqi-work** [comment]
We just split the phrases (2 to 6) in Wenetspeech M/S, it is so large for the L subset that for the scaling laws, perhaps some research will do.
